### ISSUE TITLE
非常抱歉因为这种小事打扰您！！！

### ISSUE THREAD

**Issue by Christine-xcx** [Mivinci/hugo-theme-minima#14]
请问怎么做才能替换站点图标？我将head.html中的改为 {{ $favicon := "favicon.png" }}，下面那行“<link rel="shortcut icon" href="{{ $favicon | relURL }}" type="image/x-icon" />”没有看懂注释掉了。同时themes\hugo-theme-minima\static下的文件也做了替换。但站点图标无变化。
希望没有打扰到您！非常感谢！

**Comment by Mivinci** [comment]
@Christine-xcx 没关系，感谢反馈。一直没有想到做 favicon，添加好后通知你。

**Comment by Christine-xcx** [comment]
好的！谢谢您！

**Comment by Mivinci** [comment]
哈哈哈，我写了这部分的。你要把图片转换成 `.ico` 格式再放到 static 目录下才行。在线转换工具：https://image.online-convert.com/convert-to-ico

**Comment by Mivinci** [comment]
@Christine-xcx 哈哈哈，我写了这部分的。你要把图片转换成 `.ico` 格式再放到 static 目录下才行。在线转换工具：https://image.online-convert.com/convert-to-ico

**Comment by Christine-xcx** [comment]
鞠躬感谢！！！
