### ISSUE TITLE
Missing support for line highlighting

### ISSUE THREAD

**Issue by Wirone** [Mivinci/hugo-theme-minima#20]
Hi, first of all thank you for the theme 🙂 I've started using it, but there is one feature that I miss: line highlighting.

Consider this:

```
```php {hl_lines=[5]}
<?php

class Foo {
    public function shout(): string {
        die('BAR!');
    }
}
```

`die('BAR!');` should be highlighted, but it's not because support for `.chroma .hl` is missing. I was able to override `syntax.scss` and add it but it's not that easy since code's content is not full-width and it looks weird:

<img width="640" alt="image" src="https://user-images.githubusercontent.com/600668/162592301-56b4c55c-f4d5-4ae1-b49c-5ca3e672bd8e.png">

Probably I need to override whole SASS config and use `hugo gen chromastyles` for syntax highlighting. Thanks in advance for fixing it.

**Comment by Mivinci** [comment]
Ahh… thanks for your feedback! I'll go figure out what these things are and how they work. But I guess it's not possible to fix the line highlighting because those line numbers and codes are in two separate columns generated by hugo, I can do nothing to change it's generated HTML code, but probably I'm missing something. Anyways, I will try to make it right.

**Comment by Wirone** [comment]
For the record, with `noClasses = true` it's somehow working:

<img width="640" alt="image" src="https://user-images.githubusercontent.com/600668/162593404-bd031f49-32b7-4bfc-a0dc-f2a654f517f5.png">

It looks slightly worse because line height is not working. But it is also rendered with 2 `td`s (line numbers + code) and it's full-width. So most probably it's possible to achieve it with classes 😉

**Comment by Wirone** [comment]
PS: I was able to slightly improve line highlighting by overriding `syntax.scss` and adding:

```sass
.chroma .hl {
  background-color: #585858;
}

.chroma .lnt {
  display: inline;
}
```

<img width="640" alt="image" src="https://user-images.githubusercontent.com/600668/162593956-f43ec184-8e20-4500-97f4-d3e330c82eb7.png">

Line number is also highlighted and for now it should be enough. But with full-width it would look much better IMHO 🙂

**Comment by Mivinci** [comment]
Sorry for the delay. I just got time to deal with this. Now a full-width line highlighting is available. [#5a2a7cc](https://github.com/Mivinci/hugo-theme-minima/commit/5a2a7cc35a5a13b13aa55b87fed43d6f31fc27cd)
![SSC37SNQEYFO@1DFJ)CTB@T](https://user-images.githubusercontent.com/33592375/162976382-35748bf4-96ae-487f-84aa-a2d18093167c.png)

**Comment by Wirone** [comment]
Thanks! 🍻
