### ISSUE TITLE
how to change tab size

### ISSUE THREAD

**Issue by huanggze** [Mivinci/hugo-theme-minima#26]
I have a makefile snippet like below

<img width="444" alt="image" src="https://user-images.githubusercontent.com/22350668/168959154-7d97ac98-cc41-447e-8688-d1a6531c175e.png">

it was rendered as below with tab size = 8. Is there any way to change tab size to 4, so a tab is equal to four whitespaces.

<img width="657" alt="image" src="https://user-images.githubusercontent.com/22350668/168958366-7a72a292-7161-4a34-8645-d107851cebdc.png">

**Comment by Mivinci** [comment]
Most of the renderers, including the one that Hugo uses, take a tab as an 8-spaces long indent. It is encouraged to convert a tab into 4 spaces which can be done by switching on the relevant option in your editor.

**Comment by huanggze** [comment]
Thanks for your reply. Actually, my editor GoLand works fine, it is the renderer has this indent issue.

**Comment by Mivinci** [comment]
I've tried on my VSCode with a tab and the renderer works as you expected. Does GoLand convert a tab into 4 spaces for you? I mean when you press the tab button, does it actually show in the editor as 4 plain spaces instead of a `\t`?
