### ISSUE TITLE
Does this theme style support Markdown TOC？

### ISSUE THREAD

**Issue by islongshiyu** [Mivinci/hugo-theme-minima#3]
Hi, @Mivinci 
Does this theme style support Markdown TOC ? Just like Yuque.
I do not see a post with  TOC support in example site.

**Comment by Mivinci** [comment]
@islongshiyu  Not yet. Cuz I wanted this theme to be simple. But I'll consider adding ToC on the top of each article 😊

**Comment by Mivinci** [comment]
Hi, @islongshiyu 

ToC is now supported. Add a `toc: true` in the front-matter to optionally render a ToC for a post.
