### ISSUE TITLE
photoswipe功能请求

### ISSUE THREAD

**Issue by lin-snow** [mivinci/hugo-theme-minima#58]
是否考虑给主题添加photoswipe。
这对于多张图片的展示很有帮助，并且photoswipe带有灯箱功能。
这是项目地址：[photoswipe](https://github.com/dimsemenov/PhotoSwipe/)

**Comment by mivinci** [comment]
看上去不错 但我看文档和示例说需要在包裹 `<img>` 的 `<a>` 上添加属性 `data-pswp-width` 和 `data-pswp-height`，不然图片点开显示不完整，但 Hugo 不会生成这两个东西 你看有啥好的办法可以解决吗

**Comment by mivinci** [comment]
有哪些主题也在用这个 可以嫖嫖 :)

**Comment by lin-snow** [comment]
![image](https://github.com/mivinci/hugo-theme-minima/assets/99076044/9f057022-f1d3-4c13-8063-6395db7f89c4)
目前hugo theme stack正在使用这个功能,我强烈推荐加入此功能,但是我是小白,目前还没有能力为主题贡献代码

**Comment by lin-snow** [comment]
> 

要不你去借鉴一下这个主题:https://github.com/CaiJimmy/hugo-theme-stack
