### ISSUE TITLE
Error:  parse failed. template: partials/head.html:28: unclosed action

### ISSUE THREAD

**Issue by bluretrece** [Mivinci/hugo-theme-minima#9]
Hi, I'm trying to load your theme in my blog but the following error appears: 

`Error: add site dependencies: load resources: loading templates: "/home/user/programming/blog/bluretreceblog/themes/hugo-theme-minima/layouts/partials/head.html:28:1": parse failed: template: partials/head.html:28: unclosed action`

My Hugo version is `v0.68.3/extended linux/amd64 BuildDate: 2020-03-25T06:15:45Z`. It is unclear for me what's the problem when looking at the line pointed by Hugo:

`{{ $js := resources.Get "js/main.js" | js.Build $options | resources.ExecuteAsTemplate (printf `minima.%d.js` $hash) . }}`

Any suggestion would be deeply appreciated. Thanks!

**Comment by Mivinci** [comment]
@bluretrece Thanks for the feedback! Seems like you're using hugo on linux. I haven't tested minima on any linux machine. Will let you know as soon as I find out the cause.

**Comment by bluretrece** [comment]
@Mivinci thanks for the quick response. I'll keep an eye open. I tried to update Hugo just to check if it was a compatibility issue by any chance, but it seems this is the latest version in linux.

**Comment by bluretrece** [comment]
@Mivinci it was definitely a compatibility issue. Just downloaded a fresh Hugo binary and it works just fine. Thanks for the support!

**Comment by Mivinci** [comment]
@bluretrece OK, haha!
